/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#362b4b',
        'surface-container-highest': '#3a2f50',
        'secondary-fixed': '#b4ebff',
        'secondary-fixed-dim': '#3cd7ff',
        'surface-variant': '#3a2f50',
        'tertiary-fixed': '#e6e2db',
        outline: '#a98893',
        'surface-dim': '#180d2c',
        'on-tertiary-fixed': '#1c1c18',
        'error-container': '#93000a',
        'outline-variant': '#5a3f49',
        'primary-container': '#ff45a3',
        'on-error-container': '#ffdad6',
        'on-primary-fixed': '#3e0022',
        secondary: '#a2e7ff',
        'on-primary-container': '#570032',
        'tertiary-container': '#93908b',
        'surface-tint': '#ffb0cd',
        tertiary: '#c9c6c0',
        'inverse-surface': '#ebdcff',
        'surface-container': '#251a39',
        primary: '#ffb0cd',
        'on-secondary-container': '#005669',
        'secondary-container': '#00d2fd',
        surface: '#180d2c',
        'primary-fixed': '#ffd9e4',
        'on-surface': '#ebdcff',
        'primary-fixed-dim': '#ffb0cd',
        background: '#180d2c',
        'inverse-primary': '#b7006e',
        'on-tertiary': '#31302c',
        'surface-bright': '#3f3354',
        'surface-container-high': '#2f2444',
        'on-primary-fixed-variant': '#8c0053',
        'tertiary-fixed-dim': '#c9c6c0',
        'on-secondary': '#003642',
        'surface-container-low': '#211635',
        'surface-container-lowest': '#130827',
        error: '#ffb4ab',
        'on-surface-variant': '#e1bdc8',
        'on-secondary-fixed': '#001f27',
        'on-tertiary-fixed-variant': '#484742',
        'on-error': '#690005',
        'on-background': '#ebdcff',
        'on-tertiary-container': '#2b2a25',
        'on-primary': '#640039',
        'on-secondary-fixed-variant': '#004e5f',
      },
      spacing: {
        xl: '80px',
        'container-max': '1280px',
        base: '8px',
        sm: '12px',
        gutter: '24px',
        md: '24px',
        xs: '4px',
        lg: '48px',
      },
      fontFamily: {
        lexend: ['Lexend', 'sans-serif'],
        jakarta: ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        h2: ['36px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        h3: ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        h1: ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/typography')],
};
